export const lang = {
	message: {
		"tabBar": {
			"mine": 'Me',
			"contract":"Contract",
			"trade":"Trade",
			"index":"Index",
			"assets":"Assets"
		},
		"mine":{
			"tell":"Phone",
			"Invitation":"Invite",
			"Succeed":"Copy success",
			"RealName":{
				"Certification":"Certification",
				"RealName":"Real name",
				"ID":"ID Number",
				"RealNameInput":"Please enter your real name",
				"IDInput":"Please enter your ID number",
				"Submit":"Submit",
				
				"EnterName":"Please enter your name",
				"EnterIDNumber":"Please enter your ID number",
				"IDNumberErr":"Your ID number is wrong",
				"AuthSuccess":"Successful certification!"
			},
			"SystemNotice":{
				"SystemNotice":"SystemNotice",
				"announcement":"Announcement",
				"ForDetails":"ForDetails"
			},
			"OnlinePayment":"OnlinePayment",
			"MyTeam":{
				"MyTeam":"MyTeam",
				"TeamSize":"TeamSize",
				"InviteNumber":"InviteNumber",
				"Username":"Username",
				"Phone":"Phone",
				"ContractSum":"ContractSum",
				"Level":"Level",
				"State":"State",
				"Inactive":"Inactive",
				"Offline":"Offline",
				"Certified":"Certified",
				"Scanning":"Please scan the Payment code of Alipay",
			},
			"TradeOrder":{
				"TradeOrder":"TradeOrder",
				"All":"All",
				"InTrading":"InTrading",
				"Complete":"Complete",
				"Canceled":"Canceled",
				"NoData":"No data!"
			},
			"ProblemFeedback":{
				"ProblemFeedback":"ProblemFeedback",
				"QuestionInput":"Please specify the problem you want to feedback",
				"Contact":"Contact",
				"COMMITTED":"COMMITTED"
			},
			"ServiceNode":{
				"ServiceNode":"ServiceNode",
				"NodeRules":"NodeRules",
				"ApplyNode":"ApplyForNode"
			},
			"SuperNode":{
				"SuperNode":"SuperNode",
				"DepositMoney":"DepositMoney",
				"OpenNode":"Opens nodes for subordinates",
				"PhoneInput":"Please enter your cell phone number",
				"Search":"Search"
			},
			"SetFocus":{
				"SetFocus":"SetFocus",
				
				"PayMethods":"PayMethods",
				"Management":"Management",
				"Binding":"Binding",
				
				"SafetyCenter":"SafetyCenter",
				"Modify":"Modify",
				"Password":"Password",
				"CurrentPassword":"CurrentPW",
				"CurrentPasswordInput":"Please confirm the current PW",
				"UpdatePassword":"UpdatePW",
				"NewPasswrod":"NewPw",
				"ConfirmPassword":"ConfirmPW",
				"confirmAgain":"Please enter new PW again",
				"COMMITTED":"COMMITTED",
				
				"TradePassword":"TradePW",
				"MoneyPassword":"MoneyPW",
				"NewMoneyPassword":"NewMoneyPW",
				"ConfirmNewPassword":"ConfirmNewPW",
				"MobileAuthCode":"MobileAuthCode",
				"Send":"Send",
				"NewPasswordInput":"Please enter new PW",
				"ConfirmNewPasswordInput":"Please confirm new PW",
				"AuthCodeInput":"Please enter verify code",
				
				"Set":"Set",
				"Version":"Version",
				"NewVersion":"NewVersion",
				"LogOut":"LogOut",
			},
			"AddAddress":{
				"AddUSDTAddress":"AddUSDTAddress",
				"Address":"Address",
				"InputAddress":"Please type or long press paste address",
				"Note":"Note",
				"AddAddress":"AddAddress",
				"InputSaveAddress":"Please enter saved address",
				"InputAddress-m":"Please enter address remarks",
				"AddAddressChild":{
					"TradePassword":"TradePw",
					"InputTradePassword":"Please enter transaction PW",
				}
			},
			"ApplyNode":{
				"ApplyNode":"ApplyNode",
				"CurrentLevel":"CurrentLevel",
				"User":"User",
				"ApplyLevel":"ApplyLevel",
				"ServiceNode":"ServiceNode",
				"NodeAmount":"NodeAmount",
				"AccountBalance":"AccountBalance",
				"Submit":"Submit"
			},
			"Binding":{
				"Binding":"Binding",
				"Alipay":"Alipay",
				"WeChat":"WeChat",
				"BankCard":"BankCard",
				"USADAddress":"USADAddress"
			},
			"BindingBank":{
				"BindBankCard":"BindBankCard",
				"Name":"Name",
				"AutoGain":"(After authentication, it is auto obtained)",
				"BankCard":"BankCard",
				"AccountInput":"Please enter account",
				"DepositBank":"DepositBank",
				"BankInput":"Please enter deposit bank",
				"BankAddress":"Bank address(optional)",
				"BankAddressInput":"Please enter bank address",
				"Save":"Save",
				"NameInput":"Please enter your name",
				"BankCardInput":"Please enter bank card",
			},
			"BindingUsdt":{
				"USDTAddress":"USDT Address",
				"Address":"Address",
				"AddressInput":"Please enter ERC20 wallet address",
				"AddQr":"Add QRCode for payment (optional)",
				"Save":"Save",
				"usdtAddressInput":"Please enter the USDT address"
			},
			"BindingWx":{
				"BindingWx":"Binding WeChat",
				"Name":"Name",
				"WxName":"WeChat name (Auto obtained after authentication)",
				"AccountInput":"Please enter your account",
				"AddQr":"Add QRCode for payment (optional)",
				"Save":"Save",
				"WxNameInput":"Please enter WeChat name",
				"WxAccountInput":"Please enter WeChat account"
			},
			"BindingZfb":{
				"BindingAlipay":"Binding Alipay",
				"Name":"Name",
				"AlipayName":"Alipay(Auto obtained after authentication)",
				"Account":"Account",
				"AccountInput":"Please enter account",
				"AddQr":"Add QRCode for payment (optional)",
				"Save":"Save",
				"NameInput":"Please enter Alipay name",
				"AlipayInput":"Please enter Alipay account"
			},
			"CapitalUpdate":{
				"MoneyPassword":"Money PW",
				"NewPassword":"New PW",
				"NewPasswordInput":"Please enter new PW",
				"Confirm":"Confirm NewPassword ",
				"ConfirmInput":"Please confirm new PW",
				"VerifyCode":"MobileVerifyCode",
				"CodeInput":"Please enter verify code",
				"COMMITTED":"COMMITTED",
				"Send":"Send"
			},
			"ClassAList":{
				"List":"ClassAList",
				"Username":"Username",
				"Phone":"Phone",
				"ContractSum":"ContractSum",
				"Level":"Level",
				"State":"State",
				"ClassAListChild":{
					"RegularMembers":"RegularMembers",
					"MarketNode":"MarketNode",
					"SuperNode":"SuperNode"
				},
			},
			"CoinCharging":{
				"Recharge":"Recharge",
				"SaveQR":"Save QR",
				"RechargeAddress":"Recharge address",
				"Copy":"Copy",
				"Text1":"Do not recharge any ERC20_USDT assets to the above address, otherwise the assets will not be retrieved.",
				"Text2":"After you recharge to the above address, you need the confirmation of the whole network node. After 12 network confirmations, you will receive the account, which can be reflected after 12 network confirmations.",
				"Text3":"Minimum recharge amount: 1USDT, less than the minimum amount of recharge will not be received and will not be returned.",
				"SaveSucceed":"Saved image successfully",
			},
			"CollectCoin":{
				"Withdrawal":"Withdrawal",
				"XCoin":"XCoin",
				"WithdrawalAddress":"WithdrawalAddress",
				"CopyInput":"Type or long press paste address",
				"WithdrawalAmount":"WithdrawalAmount",
				"Mini":"Minimum withdrawal amount:2",
				"All":"All",
				"Usable":"Usable",
				"ServiceCharge":"ServiceCharge",
				"Text1":"Minimum withdrawal amount:2USDT(ERC20)",
				"Text2":"In order to ensure the security of the fund, when your account security policy is changed and your password is changed, we will conduct manual audit on the withdrawal. Please wait patiently for the call or email from the customer service staff.",
				"Text3":"Do not make sure your computer or browser is secure to prevent information from being tampered with or leaked.",
				"AccountNumber":"Account number"
			},
			
			"contract":{
				"tip":"No relevant data is available",
				"XCoin":"XCoin",
				"NotOpened":"Temporarily not opened",
				"Contract":"ContractInvestment",
				"Cumulative":"TotalInvest",
				"Earnings":"TotalRevenue",
				
				"State":"State:",
				"Currency":"Currency:",
				"Number":"Contract sum:",
				"Create":"Create contract",
				"Check":"Check details",
				"Back":"Apply back",
				"Lock":"Existing contract, contract lockdown",
				"Invitation":"Ranking list"
			},
			"contractualing":{
				"Sure":"Are you sure to return the money?",
				"Cancel":"Cancel",
				"Ok":"Ok",
				"State":"State:",
				"Number":"Contract amount:",
				"Time":"Online time:",
				"Day":"Day",
				"Pending":"Pending earnings:",
				"Receive":"Receive",
				"ApplyBack":"Apply back:",
				"Apply":"Apply",
				"Check":"View log",
				"Earnings":"Please collect proceeds first",
				"Contract":"Contract investment"
			},
			"CumulativeRecord":{
				"Cumulative":"CumulativeInvestment",
				"Time":"Invest time ",
				"Level":"Investment grade"
			},
			"forgetPS":{
				"Retrieve":"RetrievePW",
				"Phone":"Phone",
				"Code":"Auth code",
				"PhoneCode":"Mobile auth code",
				"Send":"Send",
				"Set":"Set PW",
				"Confirm":"Confirm PW",
			},
			"history":{
				"History":"History",
				"Number":"Number",
				"State":"State",
				"Time":"Time",
				"No":"No"
			},
			"HistoryDetails":{
				"State":"State",
				"Address":"WithdrawalAddress",
				"ServiceCharge":"ServiceCharge",
				"Time":"Time",
				"Audit":"Audit",
				"Completed":"Completed",
				"Undone":"Undone"
			},
			"IdentifyChips":{
				"Raise":"ICO Raise",
				"Purchase":"Purchase XCoin",
				"NumberInput":"Please enter purchase quantity",
				"All":"All buy",
				"PasswordInput":"Please enter fund PW",
				"Balance":"Balance",
				"Real":"Real payment",
				"Cancel":"Cancel",
				"Confirm":"Confirm",
				
				"Price":"Offering price",
				"Number":"Issue number",
				"Residue":"Number remaining",
				"Now":"Buy now",
				"Start":"Project start time"
			},
			"Index":{
				"No":"No relevant data is available",
				"Total":"Total assets",
				"Contains":"Contains",
				"XCoin":"XCoin",
				"Contract":"Contract",
				"Mall":"Mall",
				"Raise":"ICORaise",
				"Center":"Convenient",
				"Unopen":"Unopen",
				"Notice":"System notice",
				"Assets":"Assets",
				"NV":"Number/Worth",
				"Applies":"Applies"
			},
			"information":{
				"Total":"Total assets",
				"Recharge":"Recharge",
				"Extract":"Extract",
				"Exchange":"Exchange",
				"Assets":"AssetAccount", 
				"Dynamic":"DynamicAccount", 
				"Points":"MallPoints",
				"XCoin":"XCoin",
				"FreezePurse":"FreezePurse",
				
				"Number":"Number",
				"Note":"Note",
				"Time":"Time",
				"Unfinished":"Unfinished",
				"Completed":"Completed",
				"Into":"Into", 
				"Withdrawal":"Withdrawal",
				"Contract":"ContractRevenue",
				"Invitation":"InviteReturns",
				"Team":"teamReturns",
				"Node":"NodeReturns",
				
				"Usable":"Usable",
				"Freeze":"Freeze",
				"Equivalent":"Equivalent",
				"Financial":"Financial records",
				"NoRecord":"No record",
				"Static":"Static account",
				"Redelivery":"After voting",
				"Property":"Assets"
			},
			"InvestmentRecord":{
				"Earnings":"Accumulated earnings",
				"Time":"Returns time",
				"Amount":"Income amount",
				"XCoin":"XCoin"
			},
			"InviteFriends":{
				"Invite":"Invite friends to make money",
				"InviteCode":"Invite code",
				"Save":"Save to album",
				"Copy":"Copy code",
				"Succeed":"Saved image successfully"
			},
			"login":{
				"Holle":"Holle",
				"Welcome":"Welcome to",
				"Account":"Please enter account",
				"Password":"Please enter PW",
				"Login":"Login",
				"Forgot":"Forgot PW",
				"Register":"Register",
				"NameInput":"Please enter username",
				"PasswordInput":"Please enter your PW",
			},
		},
	
		
		"NodeRules":{
			"NodeRules":"Node rules",
			"ApplyNode":"Apply node"
		},
		"notice":{
			"SystemNotice":"System notice",
			"ForDetails":"For details"
		},
		"NoticeDetails":{
			"Test":"Test",
			"ForDetails":"For details"
		},
		"order":{
			"List":"Publish list",
			"No":"No data",
			"All":"All",
			"Sell":"Sell",
			"Buy":"Buy",
			"Completed":"Completed",
			"Cancelled":"Cancelled",
			
			"Number":"Number",
			"Residue":"Residue",
			"UnitPrice":"Unit price",
			"Amount":"Amount",
			"Cancel":"Cancel",
			"XCoin":"XCoin",
			"Trading":"For trading",
			"TradingIn":"Trading in",
		},
		"OrderDetail":{
			"Appeal":"Appeal",
			"UnitPrice":"UnitPrice",
			"Number":"Number",
			"BuyersNick":"BuyersNickname",
			"BuyersName":"BuyersName",
			"SellerNick":"SellerNickname",
			"SellerName":"SellerName",
			"OrderNumber":"OrderNumber",
			"Time":"Order time",
			"Way":"Order way",
			"Check":"Check payment voucher",
			"Upload":"Upload payment voucher",
			"Wait":"Wait for Release",
			"Release":"Given operating",
			"Save":"Save image",
			"Copy":"Copy success",
			
			"Contact":"Contact each other",
			"Min":"min",
			"H":"h",
			"Content":"Complaint content",
			"Submit":"Submit complaint",
			"Cancel":"Cancel",
			"ContentInput":"Please enter the content of the complaint",
			"Success":"Complaint Success",
		},
		"OrderList":{
			"List":"Publish list",
			"All":"All",
			"TradingIn":"Tradin in",
			"Completed":"Completed",
			"Cancelled":"Cancelled",
			"Nodata":"No data",
			
			"Number":"Number",
			"Residue":"Residue",
			"UnitPrice":"UnitPrice",
			"Amount":"Amount",
			"Details":"Details",
			"Cancel":"Cancel",
			"XCoin":"XCoin",
		},
		"PasswordUpdate":{
			"Password":"Password",
			"CurrentPw":"CurrentPW",
			"InputPw":"Please enter current PW",
			"Update":"Update PW ",
			"NewPw":"Please enter new PW",
			"ConfirmPw":"ConfirmPW",
			"InputAgain":"Please enter new PW again",
			"Submit":"Submit",
			"InputOld":"Please enter old PW",
			"InputNew":"Please enter new PW",
			"AgainInputNew":"Please confirm the new PW",
			"Consistent":"Please keep the PW consistent"
		},
		"Pay":{
			"Pay":"Pay",
			"Amount":"Amount",
			"InputAmount":"Please enter the pay amount(1~300cny)",
			"Password":"Password",
			"InputPassword":"Please enter PW",
			"Balance":"Balance",
			"XCoin":"XCoin",
			"Submit":"Submit",
			"Paying":"In the pay",
			"EnterAmount":"Please enter the amount",
			"EnterPassword":"Please enter PW",
			"Transfer":"Please don't operate while transferring money"
		},
		"PetroleumEtc":{
			"Refuel":"RefuelCard",
			"Balance":"Balance",
			"Confirm":"Confirm",
			"ChargePhone":"PhoneUp",
			"Filling":"TrafficUp",
			"CNY":"CNY",
			"More":"More",
			"Increase":"To be add",
			"Unopen":"Unopen",
			
			"CPDC":"CPDC recharge",
			"CNPC":"CNPC recharge",
			"Security":"Security",
			"Amount":"Amount",
			"Poundage":"Poundage",
			"RefuelCard":"Please enter gas card number",
			"Phone":"Please enter gas card number",
			"Name":"Please enter cardholder's name",
			"Password":"Please enter fund PW",
			"Real":"RealPay",
			"ConfirmUp":"ConfirmUp"
		},
		"Problem":{
			"Content":"Please specify what you want to feedback",
			"Contact":"Contact",
			"Submit":"Submit",
			"Input":"Please enter the question you want to feedback",
			"Feedback":"Feedback"
		},
		"PutLive":{
			"Methods":"Pay way",
			"Binding":"Binding",
			"Activated":"Activated",
			"Inactive":"Inactive",
			"WeChat":"WeChat",
			"Alipay":"Alipay"
		},
		"RankingList":{
			"Overall":"OverallRanking",
			"Nickname":"Nickname",
			"Phone":"Phone",
			"Ranking":"Ranking",
			
		},
		"ReceiveRecord":{
			"Record":"Record",
			"Time":"Time",
			"Amount":"Amount",
			"XCoin":"XCoin",
		},
		"register":{
			"CreateXCOIN":"CreateXCOIN",
			"Nickname":"Nickname",
			"InputNickname":"Please enter nickname",
			"Phone":"Phone",
			"InputPhone":"Please enter phone",
			"Password":"Password",
			"InputPassword":"Please enter PW",
			"AgainPassword":"Please enter PW again",
			"Invite":"InviteCode",
			"InputInvite":"Please enter InviteCode",
			"Auth":"AuthCode",
			"InputAuth":"Please enter AuthCode",
			"Mobile":"MobileCode",
			"InputMobile":"Please enter MobileCode",
			"Create":"Create",
			"Error":"Phone Error",
			"Send":"Send",
			"Empty":"The phone cannot be empty",
			"AuthErr":"Auth code error"
		},
		"SecurityCenter":{
			"Center":"Security center",
			"LoginPw":"Login PW",
			"Update":"Modify",
			"TradingPw":"Trade password",
			"Set":"Set",
		},
		"SetUp":{
			"Way":"Receipt Way",
			"MGMT":"MGMT",
			"Center":"Security center",
			"Modify":"Modify",
			"Version":"Version: ",
			"New":"New version",
			"Logout":"LogOut"
		},
		"StartSuperNode":{
			"Open":"Open SuperNode",
			"Confirm":"Confirm Pay"
		},
		"Supernode":{
			"SuperNode":"SuperNode",
			"For":"Open node for sub",
			"InputPhone":"Please enter your phone",
			"Search":"Search",
			"Open":"OpenSVIP",
			"Deposit":"Deposit money"
		},
		"TeamList":{
			"List":"TeamList",
			"People":"People",
			"SuperNode":"SuperNode",
			"Common":"CommonVip",
			"Market":"MarketNode",
			"NodeVip":"NodeVip"
		},
		"TellCost":{
			"Center":"Top up center",
			"InputPhone":"Please enter your phone",
			"Phone":"Prepaid phone",
			"Three":"(Three netcom use)",
			"Balance":"Balance",
			"Now":"Top up Now",
			"Oil":"Oil Up",
			"Traffic":"Traffic Up",
			"CNY":"CNY",
			"Unopen":"Unopen",
			
			"Verify":"Verify",
			"Cancel":"Cancel",
			"AmountUp":"AmountUp",
			"Poundage":"Poundage",
			"InputPw":"Please enter fund PW",
			"RealPay":"Real pay",
			"Confirm":"Confirm"
		},
		"transaction":{
			"OTC":"OTC Trading",
			"XCoin":"XCoin",
			"Release":"Release",
			"Coin":"Coin trading",
			"Fiat":"Fiat deal",
			"Buy":"Buy",
			"Nodata":"No data",
			"Sell":"Sell",
			"Refresh":"Refresh the success",
			"Load":"Load the success",
			
			"ReleaseOrder":"ReleaseOrder",
			"ReleaseSell":"ReleaseSell",
			"ReleaseBuy":"ReleaseBuy",
			"Currency":"Currency",
			"Price":"Please enter unit price",
			"Unit":"U.P.",
			"InputNumber":"Please enter quantity",
			"All":"All sold",
			"Number":"Number",
			"Limit":"Limit",
			"InputPw":"Please enter PW",
			"Total":"Total",
			"Real":"Real pay",
			"Cancel":"s late auto cancel",
			"Confirm":"Confirm",
			
			"NowPrice":"NowPrice",
			"DealsNumber":"DealsNumber",
			"Input":"please enter",
			"DealsAmount":"DealsAmount",
			"Legal":"LegalTender",
			"Usable":"Usable",
			"Amount":"Amount",
			"ForPay":"ForThePay",
			"Wallet":"Wallet",
			
			"To":"InNumber",
			"Place":"Place",
			"Norm":"Norm",
			"AllBuy":"AllBuy",
			
			"Click":"Click load more……",
			"Type":"Type",
			"Time":"Time",
			"Prices":"Price",
			"Operation":"Operation",
			"Completed":"Completed",
		},
		"transfer":{
			"Exchange":"Exchange",
			"From":"From",
			"Usable":"Usable",
			"To":"To",
			"Type":"Currency",
			"XCoin":"XCoin",
			"Nubmer":"Nubmer",
			"InputNumber":"Please enter exchange quantity",
			"All":"All",
			"Text":"Transactions can only be made by converting assets into corresponding accounts. There is no handling charge for transfers between accounts.",
			"Voting":"XCoinVoting",
			"Mall":"Mall points",
			"Roll":"Please enter the number of transfers"
		},
		"USDTAddress":{
			"Address":"Address",
			"NoRecord":"NoRecord",
			"AddAddress ":"AddAddress"
		},
		"Quotation":{
			"Market":"Market",
			"ServiceCenter":"ServiceCenter",
			"Name ":"Name",
			"New":"NewPrice",
			"Applies":"Applies",
			"NoData":'No Data'
		},
	}
}
